#!/usr/bin/env node
/**
 * Bootstrap ops@curxor.ai local bridge env:
 *   config/local/ops-digital.env  (gitignored, CTO-managed)
 *   pillar-4-dashboard/.env.local  → CURXOR_DIGITAL_ENV_PATH + dev-qa JSON paths
 *
 * Usage (from pillar-4-dashboard): npm run setup:ops-env
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DASHBOARD = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(DASHBOARD, "..");
const DEV_QA = path.join(DASHBOARD, "scripts", "dev-qa");
const OPS_EXAMPLE = path.join(REPO_ROOT, "config", "local", "ops-digital.env.example");
const OPS_ENV = path.join(REPO_ROOT, "config", "local", "ops-digital.env");
const ENV_LOCAL = path.join(DASHBOARD, ".env.local");

const devQaPaths = `
CURXOR_FRE_STATE_PATH=${path.join(DEV_QA, "fre-state.json")}
CURXOR_USER_SETTINGS_PATH=${path.join(DEV_QA, "user-settings.json")}
CURXOR_CAPITAL_QUEUE_PATH=${path.join(DEV_QA, "capital-queue.json")}
CURXOR_CAPITAL_PFM_PATH=${path.join(DEV_QA, "capital-pfm.json")}
CURXOR_CAPITAL_INTEL_PATH=${path.join(DEV_QA, "capital-intel.json")}
CURXOR_CAPITAL_PLAID_PATH=${path.join(DEV_QA, "capital-plaid.json")}
CURXOR_CAPITAL_SNAPTRADE_PATH=${path.join(DEV_QA, "capital-snaptrade.json")}
CURXOR_DIGITAL_ENV_PATH=${OPS_ENV}
CURXOR_WORK_GOOGLE_OAUTH_PATH=${path.join(DEV_QA, "work-google-oauth.json")}
CURXOR_WORK_MICROSOFT_OAUTH_PATH=${path.join(DEV_QA, "work-microsoft-oauth.json")}
CURXOR_WORK_NOTION_OAUTH_PATH=${path.join(DEV_QA, "work-notion-oauth.json")}
CURXOR_GARMIN_OAUTH_PATH=${path.join(DEV_QA, "garmin-oauth.json")}
CURXOR_FAMILY_PROFILES_PATH=${path.join(DEV_QA, "family-profiles.json")}
CURXOR_APP_FRE_DIR=${path.join(DEV_QA, "app-fre")}
CURXOR_VITAL_STATE_PATH=${path.join(DEV_QA, "vital-health.json")}
CURXOR_CLAW_CONTEXT_PATH=${path.join(DEV_QA, "claw-context.json")}
CURXOR_HUMANOID_HUB_PATH=${path.join(DEV_QA, "humanoid-hub.json")}
CURXOR_BRIDGE_HEALTH_PATH=${path.join(DEV_QA, "content-bridge-health.json")}
`.trim();

function upsertEnvLocal() {
  const header = `# CurXor local dev — generated by setup-ops-env.mjs (ops@curxor.ai)
# Secrets: edit config/local/ops-digital.env only — never commit
${devQaPaths}
PORT=3080
HOSTNAME=127.0.0.1
`;

  if (!existsSync(ENV_LOCAL)) {
    writeFileSync(ENV_LOCAL, header, "utf8");
    console.log(`Created ${ENV_LOCAL}`);
    return;
  }

  let content = readFileSync(ENV_LOCAL, "utf8");
  if (content.includes("CURXOR_DIGITAL_ENV_PATH")) {
    if (!content.includes(OPS_ENV)) {
      content = content.replace(
        /CURXOR_DIGITAL_ENV_PATH=.+/,
        `CURXOR_DIGITAL_ENV_PATH=${OPS_ENV}`,
      );
      writeFileSync(ENV_LOCAL, content, "utf8");
      console.log(`Updated CURXOR_DIGITAL_ENV_PATH → ops-digital.env in ${ENV_LOCAL}`);
    } else {
      console.log(`${ENV_LOCAL} already points at ops-digital.env`);
    }
    return;
  }

  writeFileSync(ENV_LOCAL, `${content.trim()}\n\n${header}`, "utf8");
  console.log(`Appended ops paths to ${ENV_LOCAL}`);
}

function main() {
  if (!existsSync(OPS_EXAMPLE)) {
    console.error(`Missing template: ${OPS_EXAMPLE}`);
    process.exit(1);
  }

  if (!existsSync(OPS_ENV)) {
    copyFileSync(OPS_EXAMPLE, OPS_ENV);
    console.log(`Created ${OPS_ENV}`);
    console.log("  → Paste ops@curxor.ai bridge keys from provider dashboards.\n");
  } else {
    console.log(`Exists ${OPS_ENV}\n`);
  }

  upsertEnvLocal();

  console.log("\nNext steps:");
  console.log("  1. Edit config/local/ops-digital.env (never commit, never paste in chat)");
  console.log("  2. npm run dev");
  console.log("  3. Settings → Integrations or Claw vaults → verify bridge health");
  console.log("  See config/local/README.md\n");
}

main();
