import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

import type { ClawProfile } from "./claw-recommend";

const execFileAsync = promisify(execFile);

export function getActiveClawConfPath(): string {
  return process.env.CURXOR_ACTIVE_CLAW_CONF ?? "/etc/curxor/engine.env.d/active-claw.conf";
}

/** Stable 1–255 claw id for motor wire format. */
export function clawIdFromProfileId(profileId: string): number {
  let hash = 0;
  for (let i = 0; i < profileId.length; i++) {
    hash = (Math.imul(31, hash) + profileId.charCodeAt(i)) >>> 0;
  }
  return (hash % 254) + 1;
}

function inferBackend(profile: ClawProfile): "ollama" | "vllm" {
  if (profile.models.vla) return "vllm";
  return "ollama";
}

function inferenceModel(profile: ClawProfile): string {
  if (profile.models.vla) return profile.models.vla;
  return profile.models.reasoning;
}

export async function writeActiveClawEnv(profile: ClawProfile): Promise<void> {
  const filePath = getActiveClawConfPath();
  await mkdir(path.dirname(filePath), { recursive: true });

  const backend = inferBackend(profile);
  const lines = [
    "# CurXor active claw — generated by dashboard; do not edit by hand",
    `CURXOR_CLAW_ID=${clawIdFromProfileId(profile.id)}`,
    `CURXOR_INFERENCE_BACKEND=${backend}`,
    `CURXOR_INFERENCE_MODEL=${inferenceModel(profile)}`,
    `CURXOR_VISION_MODEL=${profile.models.vision}`,
    `CURXOR_AGENT_SYSTEM_PROMPT=You are ${profile.name}, a sovereign edge claw agent. Intent: ${profile.intent.replace(/\s+/g, " ").slice(0, 240)}. Output only physical motor actions via tools.`,
  ];

  await writeFile(filePath, `${lines.join("\n")}\n`, { mode: 0o644 });
}

export async function restartEngineForActiveClaw(): Promise<void> {
  const script = process.env.CURXOR_APPLY_CLAW_SCRIPT ?? "/opt/curxor/scripts/apply-active-claw.sh";
  try {
    await execFileAsync("sudo", [script], { timeout: 15_000 });
  } catch (error) {
    console.error("[curxor-dashboard] engine restart skipped:", error);
  }
}
