#!/usr/bin/env bash
# CurXor OS — Captive Portal Network Trap (smart-hub mode)
#
# Configures dnsmasq on the Command Port NIC (user-facing LAN) and iptables redirects so
# connected clients receive DHCP, captive-portal probe DNS only (not wildcard internet
# hijack), and hit the Next.js dashboard on port 3080 via HTTP/HTTPS.
#
# The Egress/mesh NIC is NEVER touched — robotics mesh stays isolated.
#
# Usage: sudo /opt/curxor/scripts/setup-captive-portal.sh
set -euo pipefail

CURXOR_ROOT="${CURXOR_ROOT:-/opt/curxor}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/network-defaults.sh
source "${SCRIPT_DIR}/lib/network-defaults.sh"

# ── Network profile (Command Port / Egress Port roles) ───────────────────────
USER_LAN_IFACE="${CURXOR_USER_LAN_IFACE}"
MESH_IFACE="${CURXOR_MESH_IFACE}"
APPLIANCE_IP="${CURXOR_APPLIANCE_IP}"
APPLIANCE_CIDR="${CURXOR_APPLIANCE_CIDR}"
DASHBOARD_PORT="${CURXOR_DASHBOARD_PORT:-3080}"

DNSMASQ_DROPIN="/etc/dnsmasq.d/curxor-captive.conf"
NETPLAN_DROPIN="/etc/netplan/99-curxor-captive-command.yaml"
IPTABLES_COMMENT="curxor-captive"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

echo "==> CurXor Captive Portal Setup"
echo "    User LAN   : ${USER_LAN_IFACE} @ ${APPLIANCE_IP}"
echo "    Mesh (off) : ${MESH_IFACE} — not modified"
echo "    Dashboard  : 127.0.0.1:${DASHBOARD_PORT}"

# ── Preflight ─────────────────────────────────────────────────────────────────
if [[ ! -d "/sys/class/net/${USER_LAN_IFACE}" ]]; then
  echo "ERROR: Interface '${USER_LAN_IFACE}' not found." >&2
  exit 1
fi

if [[ ! -d "/sys/class/net/${MESH_IFACE}" ]]; then
  echo "WARN: Mesh interface '${MESH_IFACE}' not found — continuing (egress NIC check skipped)."
fi

mkdir -p "${CURXOR_ROOT}/scripts" "${CURXOR_ROOT}/config/captive-portal"

# ── Packages ──────────────────────────────────────────────────────────────────
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends \
  dnsmasq \
  iptables \
  iptables-persistent \
  netfilter-persistent \
  iproute2 \
  netplan.io

# ── Static IP on Command Port (user-facing captive LAN) ─────────────────────
cat > "${NETPLAN_DROPIN}" <<EOF
# CurXor OS — captive portal user LAN (${USER_LAN_IFACE} only)
network:
  version: 2
  ethernets:
    ${USER_LAN_IFACE}:
      addresses:
        - ${APPLIANCE_CIDR}
      optional: true
EOF
chmod 600 "${NETPLAN_DROPIN}"
netplan generate
netplan apply

ip link set "${USER_LAN_IFACE}" up
if ! ip -4 -o addr show dev "${USER_LAN_IFACE}" | grep -q "${APPLIANCE_IP}/"; then
  ip addr add "${APPLIANCE_CIDR}" dev "${USER_LAN_IFACE}" 2>/dev/null || true
fi

# ── dnsmasq — Command Port only; isolated LAN (no internet hijack) ───────────
# DHCP: address + mask only — no default gateway, no DNS push (dual-homed laptops
# keep Wi-Fi internet). Captive pop-up uses probe domains + iptables :80/:443.
DOMAINS_FILE="${CURXOR_ROOT}/config/captive-portal/captive-dns-domains.txt"
if [[ ! -f "${DOMAINS_FILE}" ]]; then
  DOMAINS_FILE="${SCRIPT_DIR}/../config/captive-portal/captive-dns-domains.txt"
fi

{
  cat <<EOF
# CurXor OS — generated by setup-captive-portal.sh
interface=${USER_LAN_IFACE}
bind-interfaces
except-interface=lo
except-interface=${MESH_IFACE}
listen-address=${APPLIANCE_IP}
dhcp-range=10.0.0.50,10.0.0.250,255.255.255.0,12h
# No option:router — Command Port is not an internet gateway for clients.
# No option:dns-server — avoids poisoning dual-homed laptop DNS on Wi-Fi.
no-resolv
no-hosts
EOF
  if [[ -f "${DOMAINS_FILE}" ]]; then
  while IFS= read -r domain || [[ -n "${domain}" ]]; do
    domain="${domain%%#*}"
    domain="$(echo "${domain}" | xargs)"
    [[ -z "${domain}" ]] && continue
    printf 'address=/%s/%s\n' "${domain}" "${APPLIANCE_IP}"
  done < "${DOMAINS_FILE}"
  fi
} > "${DNSMASQ_DROPIN}"
chmod 0644 "${DNSMASQ_DROPIN}"

# Prevent systemd-resolved from binding :53 globally (conflicts with dnsmasq)
if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
  mkdir -p /etc/systemd/resolved.conf.d
  cat > /etc/systemd/resolved.conf.d/curxor-captive.conf <<'EOF'
[Resolve]
DNSStubListener=no
EOF
  systemctl restart systemd-resolved
fi

# Disable default dnsmasq config fragments that bind all interfaces
if [[ -f /etc/dnsmasq.conf ]]; then
  if ! grep -q "^# CurXor: disabled by setup-captive-portal" /etc/dnsmasq.conf; then
    sed -i 's/^port=/\#port=/' /etc/dnsmasq.conf 2>/dev/null || true
    sed -i 's/^interface=/\#interface=/' /etc/dnsmasq.conf 2>/dev/null || true
    sed -i 's/^bind-interfaces/\#bind-interfaces/' /etc/dnsmasq.conf 2>/dev/null || true
    sed -i 's/^bind-dynamic/\#bind-dynamic/' /etc/dnsmasq.conf 2>/dev/null || true
  fi
fi

systemctl enable dnsmasq
systemctl restart dnsmasq

# ── iptables — redirect Command Port :80/:443 → localhost:3080 ──────────────
remove_curxor_rules() {
  local table=$1
  local chain=$2
  while iptables -t "${table}" -L "${chain}" -n --line-numbers 2>/dev/null | grep -q "${IPTABLES_COMMENT}"; do
    local line
    line="$(iptables -t "${table}" -L "${chain}" -n --line-numbers | grep "${IPTABLES_COMMENT}" | head -1 | awk '{print $1}')"
    iptables -t "${table}" -D "${chain}" "${line}" 2>/dev/null || break
  done
}

# Idempotent re-run: strip prior CurXor rules
remove_curxor_rules nat PREROUTING
remove_curxor_rules filter INPUT

# HTTP/HTTPS on user LAN → Next.js dashboard
iptables -t nat -A PREROUTING -i "${USER_LAN_IFACE}" -p tcp --dport 80 \
  -m comment --comment "${IPTABLES_COMMENT}" \
  -j REDIRECT --to-ports "${DASHBOARD_PORT}"

iptables -t nat -A PREROUTING -i "${USER_LAN_IFACE}" -p tcp --dport 443 \
  -m comment --comment "${IPTABLES_COMMENT}" \
  -j REDIRECT --to-ports "${DASHBOARD_PORT}"

# Allow redirected traffic to reach Node listener
iptables -A INPUT -i "${USER_LAN_IFACE}" -p tcp --dport "${DASHBOARD_PORT}" \
  -m comment --comment "${IPTABLES_COMMENT}" \
  -j ACCEPT

iptables -A INPUT -i "${USER_LAN_IFACE}" -p udp --dport 67 \
  -m comment --comment "${IPTABLES_COMMENT}" \
  -j ACCEPT

iptables -A INPUT -i "${USER_LAN_IFACE}" -p udp --dport 53 \
  -m comment --comment "${IPTABLES_COMMENT}" \
  -j ACCEPT

iptables -A INPUT -i "${USER_LAN_IFACE}" -p tcp --dport 53 \
  -m comment --comment "${IPTABLES_COMMENT}" \
  -j ACCEPT

# ── Persist iptables across reboot ────────────────────────────────────────────
mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6 2>/dev/null || true
netfilter-persistent save
systemctl enable netfilter-persistent

# ── Verification ──────────────────────────────────────────────────────────────
echo ""
echo "==> Captive portal active"
echo "    dnsmasq      : $(systemctl is-active dnsmasq) on ${USER_LAN_IFACE}"
echo "    DHCP range   : 10.0.0.50 – 10.0.0.250 (no router/DNS push)"
echo "    Captive DNS  : probe domains only (see config/captive-portal/captive-dns-domains.txt)"
echo "    HTTP redirect: ${USER_LAN_IFACE}:80  → 127.0.0.1:${DASHBOARD_PORT}"
echo "    HTTPS redirect: ${USER_LAN_IFACE}:443 → 127.0.0.1:${DASHBOARD_PORT}"
echo ""
echo "    COMMAND clients: open http://${APPLIANCE_IP}:${DASHBOARD_PORT}/home"
echo "    Dual-homed laptops: run setup-laptop-command-port.ps1 (Windows) once per cable plug."
echo "    Robotics mesh (${MESH_IFACE}) remains untouched."
echo ""
ss -lun "sport = :53" 2>/dev/null | grep -E "${APPLIANCE_IP}|${USER_LAN_IFACE}" || true
iptables -t nat -L PREROUTING -n -v | grep "${IPTABLES_COMMENT}" || true
