#!/usr/bin/env bash
# CurXor OS — Egress Port WAN (dual-IP on mesh NIC)
#
# Keeps robotics mesh @ 10.77.0.1 AND DHCP from the home router on the same NIC
# so Digital Bridges, OTA, and frontier Patron can reach the internet.
#
# Prerequisite: Egress cable → router (Part 4). Command Port stays isolated.
#
# Usage: sudo /opt/curxor/scripts/setup-egress-wan.sh
set -euo pipefail

if grep -q $'\r' "$0" 2>/dev/null; then
  sed -i 's/\r$//' "$0"
  exec bash "$0" "$@"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/network-defaults.sh
source "${SCRIPT_DIR}/lib/network-defaults.sh"

MESH_IFACE="${CURXOR_MESH_IFACE}"
MESH_IP="${CURXOR_MESH_BIND_IP}"
MESH_CIDR="${CURXOR_MESH_CIDR}"
NETPLAN_WAN="/etc/netplan/99-curxor-egress-wan.yaml"
NETPLAN_MESH_ONLY="/etc/netplan/99-curxor-mesh.yaml"
FLAG_FILE="${CURXOR_EGRESS_WAN_FLAG:-/var/lib/curxor/.egress-wan-enabled}"
BROKER_ENV="/etc/curxor/telemetry-broker.env"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

if ! ip link show "${MESH_IFACE}" &>/dev/null; then
  echo "ERROR: interface ${MESH_IFACE} not found — cable Egress Port to router first." >&2
  exit 1
fi

mkdir -p "$(dirname "${FLAG_FILE}")"

echo "==> CurXor egress WAN on ${MESH_IFACE}"
echo "    Mesh (static) : ${MESH_IP}/${MESH_CIDR}"
echo "    Router (DHCP) : dhcp4 on same NIC"

cat > "${NETPLAN_WAN}" <<EOF
# CurXor OS — Egress Port: mesh + router WAN (dual-IP). Generated by setup-egress-wan.sh
network:
  version: 2
  ethernets:
    ${MESH_IFACE}:
      dhcp4: true
      dhcp6: false
      optional: true
      addresses:
        - ${MESH_IP}/${MESH_CIDR}
      dhcp4-overrides:
        route-metric: 100
EOF
chmod 600 "${NETPLAN_WAN}"

if [[ -f "${NETPLAN_MESH_ONLY}" ]]; then
  rm -f "${NETPLAN_MESH_ONLY}"
  echo "    Removed ${NETPLAN_MESH_ONLY} (superseded by dual-IP egress WAN)"
fi

if command -v netplan &>/dev/null; then
  netplan apply
else
  echo "WARN: netplan not found — applying addresses manually" >&2
  ip link set "${MESH_IFACE}" up
  ip addr replace "${MESH_IP}/${MESH_CIDR}" dev "${MESH_IFACE}" 2>/dev/null || \
    ip addr add "${MESH_IP}/${MESH_CIDR}" dev "${MESH_IFACE}"
  dhclient -v "${MESH_IFACE}" 2>/dev/null || true
fi

# Pin broker to mesh IP (not router DHCP address when dual-IP).
mkdir -p /etc/curxor
if [[ -f "${BROKER_ENV}" ]]; then
  if grep -q "^CURXOR_MESH_BIND_IP=" "${BROKER_ENV}"; then
    sed -i "s|^CURXOR_MESH_BIND_IP=.*|CURXOR_MESH_BIND_IP=${MESH_IP}|" "${BROKER_ENV}"
  else
    echo "CURXOR_MESH_BIND_IP=${MESH_IP}" >> "${BROKER_ENV}"
  fi
else
  echo "CURXOR_MESH_BIND_IP=${MESH_IP}" > "${BROKER_ENV}"
  chmod 640 "${BROKER_ENV}"
fi

touch "${FLAG_FILE}"
chmod 644 "${FLAG_FILE}"

echo "==> Waiting for DHCP / default route (up to 15s)…"
for _ in $(seq 1 15); do
  if ip route show default 2>/dev/null | grep -q .; then
    break
  fi
  sleep 1
done

echo "==> Routes"
ip route show default 2>/dev/null || echo "    (no default route yet — check Egress cable → router)"
ip -4 -o addr show dev "${MESH_IFACE}" 2>/dev/null | sed 's/^/    /' || true

echo "==> DNS"
if command -v resolvectl &>/dev/null; then
  resolvectl status "${MESH_IFACE}" 2>/dev/null | head -8 | sed 's/^/    /' || true
elif [[ -f /etc/resolv.conf ]]; then
  head -5 /etc/resolv.conf | sed 's/^/    /'
fi

echo "==> HTTPS egress probe"
if curl -sf --max-time 10 -o /dev/null https://cloudflare.com/cdn-cgi/trace; then
  echo "==> Egress WAN OK"
else
  echo "WARN: HTTPS probe failed — mesh IP is up but router path may be down." >&2
  echo "      Check: Egress cable → router LAN, router DHCP enabled, link up on ${MESH_IFACE}" >&2
  exit 1
fi

if systemctl is-active --quiet curxor-telemetry-broker 2>/dev/null; then
  echo "==> Restarting telemetry broker (mesh bind refresh)"
  systemctl restart curxor-telemetry-broker || true
fi

echo "==> Flag: ${FLAG_FILE}"
echo "    post-update will re-apply egress WAN when this flag exists."
