#!/usr/bin/env bash
# CurXor — Unbox day cheat sheet (paste into terminal on MS-S1)
# Full playbook: docs/curxor-os/PRE-UNBOX-48H.md
set -euo pipefail

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  CurXor MS-S1 MAX — Unbox Day (v0.9.1)                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "1. INVENTORY"
echo "   sudo chmod +x /opt/curxor/scripts/verify-unbox-day.sh"
echo "   sudo /opt/curxor/scripts/verify-unbox-day.sh"
echo ""
echo "2. BIOS — UMA max · enp98s0=Command · enp97s0=Egress"
echo "   docs/guides/10-ms-s1-max-hardware-bios.md"
echo ""
echo "3. INSTALL (path A — clean Ubuntu 24.04 preferred)"
echo "   sudo rsync -a /path/to/curxor-os/ /opt/curxor/"
echo "   cd /opt/curxor && sudo bash scripts/install-all.sh"
echo "   # Pro 128: sudo cp pillar-1-compute/config/compute.env.pro128.example /etc/curxor/compute.env"
echo "   sudo /opt/curxor/pillar-1-compute/scripts/deploy.sh --pull-models"
echo "   sudo /opt/curxor/scripts/verify-unbox-day.sh --post-models"
echo ""
echo "4. STACK HEALTH"
echo "   systemctl status curxor-dashboard curxor-engine curxor-telemetry-broker"
echo "   curl -s http://127.0.0.1:3080/api/setup/status | jq ."
echo ""
echo "5. UAT (laptop on COMMAND cable)"
echo "   http://10.0.0.1:3080/home → Capital, Creator, Work, Forge"
echo "   Claw Cafe → Ascension → Sync"
echo ""
echo "6. ON-DEVICE SMOKE"
echo "   cd /opt/curxor/pillar-4-dashboard"
echo "   sudo -u curxor NODE_ENV=production node scripts/qa-smoke.mjs http://127.0.0.1:3080"
echo ""
echo "7. PASTE GOLDEN PATH NOTES from verify-unbox-day.sh into install addendum"
echo ""
echo "Gate on dev machine must be PASS before rsync — see pre-unbox-gate-log.txt"
